package com.xuexi.settings.mapper;

import com.xuexi.settings.domain.DicType;

import java.util.List;

public interface DicTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbg.generated Tue May 24 07:20:23 CST 2022
     */
    int deleteByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbg.generated Tue May 24 07:20:23 CST 2022
     */
    int insert(DicType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbg.generated Tue May 24 07:20:23 CST 2022
     */
    int insertSelective(DicType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbg.generated Tue May 24 07:20:23 CST 2022
     */
    DicType selectByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbg.generated Tue May 24 07:20:23 CST 2022
     */
    int updateByPrimaryKeySelective(DicType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbg.generated Tue May 24 07:20:23 CST 2022
     */
    int updateByPrimaryKey(DicType record);



}