package com.xuexi.settings.mapper;

import com.xuexi.settings.domain.User;

import java.util.List;
import java.util.Map;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbg.generated Mon Apr 11 18:24:48 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbg.generated Mon Apr 11 18:24:48 CST 2022
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbg.generated Mon Apr 11 18:24:48 CST 2022
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbg.generated Mon Apr 11 18:24:48 CST 2022
     */
    User selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbg.generated Mon Apr 11 18:24:48 CST 2022
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbg.generated Mon Apr 11 18:24:48 CST 2022
     */
    int updateByPrimaryKey(User record);

    /**
     * 根据账号和密码来查找相关的用户
     * @param map   里面保存了 相关的信息
     * @return
     */
    User SelectByLoginActAndLoginPwd(Map<String,Object> map);

    /**
     * 查询所有的用户
     * @return
     */
    List<User> SelectAllUser();
}